"""GitHub hook to check code coverage before allowing a push."""

#!/usr/bin/env python3
import json
import re
import subprocess
import sys
from pathlib import Path

THRESHOLD = 85.71


def fail(message: str, reason: str) -> None:
    """Helper to emit a block decision with a message and reason."""
    output = {
        "continue": False,
        "systemMessage": message,
        "stopReason": message,
        "reason": reason,
    }
    sys.stdout.write(json.dumps(output))
    sys.exit(0)


def main() -> None:
    """Main entry point for the check push coverage hook."""
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        print(json.dumps({"continue": True}))
        return

    command = payload.get("tool_input", {}).get("command", "")
    if not re.search(r"\bgit\s+push\b", command):
        print(json.dumps({"continue": True}))
        return

    repo_root = Path(__file__).resolve().parents[2]
    pytest_cmd = ["python3", "-m", "pytest", "-q", "-m", "not runtime"]

    try:
        subprocess.run(
            pytest_cmd,
            cwd=repo_root,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        fail(
            "Push blocked because tests failed before git push.",
            exc.stderr.strip() or "pytest failed while validating coverage.",
        )

    coverage_file = repo_root / "coverage.xml"
    if not coverage_file.exists():
        fail(
            "Push blocked because coverage results could not be found.",
            "coverage.xml was not generated by pytest.",
        )

    try:
        import xml.etree.ElementTree as ET

        tree = ET.parse(coverage_file)
        root = tree.getroot()
        line_rate = float(root.attrib.get("line-rate", "0"))
        coverage_pct = line_rate * 100.0
    except Exception as exc:
        fail(
            "Push blocked because coverage parsing failed.",
            str(exc),
        )

    if coverage_pct + 1e-9 < THRESHOLD:
        fail(
            f"Push blocked because code coverage dropped below {THRESHOLD:.2f}% (current {coverage_pct:.2f}%).",
            f"Coverage {coverage_pct:.2f}% is below threshold {THRESHOLD:.2f}%.",
        )

    print(json.dumps({"continue": True}))


if __name__ == "__main__":
    main()
