"""Configuration loading for rrt."""

import sys
from typing import TYPE_CHECKING

from . import core as _core

if TYPE_CHECKING:
    from .core import (
        _VALID_LANGUAGES,
        AUTODETECTED_CONFIG_BASENAME,
        CONFIG_FILE_CANDIDATES,
        CONFIG_SECTION_BY_FILE,
        DEFAULT_CHANGELOG,
        DEFAULT_CHANGELOG_WORKFLOW,
        DEFAULT_INIT_CONFIG,
        DEFAULT_LOCK_COMMAND,
        DEFAULT_RELEASE_BRANCH,
        GENERIC_TOOL_RRT_EXAMPLE,
        GO_TOOL_RRT_EXAMPLE,
        NODE_TOOL_RRT_EXAMPLE,
        PYTHON_TOOL_RRT_EXAMPLE,
        RUST_TOOL_RRT_EXAMPLE,
        VALID_CHANGELOG_WORKFLOWS,
        VALID_CI_FORMATS,
        VALID_TARGET_KINDS,
        ArtifactTarget,
        CommandGroupEntry,
        DocsConfig,
        EolConfig,
        EolOverride,
        FolderPolicyConfig,
        FolderRule,
        FolderScaffoldFile,
        FolderTemplate,
        GeneratedAsset,
        MapConfig,
        MissingRrtConfigError,
        PinTarget,
        PublishTarget,
        RrtConfig,
        SharedBlock,
        TopicPageEntry,
        VersionGroup,
        VersionTarget,
        _autodetect_version_targets,
        _describe_version_target,
        _detect_lock_and_files,
        _find_python_version_files,
        _json_string_field_exists,
        _load_raw_config,
        _recommended_lock_settings,
        _render_recommended_rrt_dict,
        _render_recommended_rrt_toml,
        _target_ecosystem,
        _toml_string_field_exists,
        auto_detect_config,
        autodetect_config,
        find_changelog_file,
        find_config_file,
        find_explicit_config_file,
        find_repo_root,
        format_autodetected_config_notice,
        format_missing_tool_rrt_guidance,
        ignore_dir_names,
        is_missing_tool_rrt_error,
        iter_config_files,
        load_config,
        load_config_from_path,
        load_extra_branch_types,
        load_or_autodetect_config,
        load_primary_remote,
        recommend_init_config,
        recommend_init_config_for_go,
        recommend_init_section_for_cargo,
        recommend_init_section_for_node,
        recommend_init_section_for_pyproject,
    )

    _TYPE_CHECK_EXPORTS = (
        _VALID_LANGUAGES,
        AUTODETECTED_CONFIG_BASENAME,
        CONFIG_FILE_CANDIDATES,
        CONFIG_SECTION_BY_FILE,
        DEFAULT_CHANGELOG,
        DEFAULT_CHANGELOG_WORKFLOW,
        DEFAULT_INIT_CONFIG,
        DEFAULT_LOCK_COMMAND,
        DEFAULT_RELEASE_BRANCH,
        GENERIC_TOOL_RRT_EXAMPLE,
        GO_TOOL_RRT_EXAMPLE,
        NODE_TOOL_RRT_EXAMPLE,
        PYTHON_TOOL_RRT_EXAMPLE,
        RUST_TOOL_RRT_EXAMPLE,
        VALID_CHANGELOG_WORKFLOWS,
        VALID_CI_FORMATS,
        VALID_TARGET_KINDS,
        CommandGroupEntry,
        DocsConfig,
        EolConfig,
        EolOverride,
        FolderPolicyConfig,
        FolderRule,
        FolderScaffoldFile,
        FolderTemplate,
        GeneratedAsset,
        ArtifactTarget,
        MapConfig,
        MissingRrtConfigError,
        PinTarget,
        PublishTarget,
        RrtConfig,
        SharedBlock,
        TopicPageEntry,
        VersionGroup,
        VersionTarget,
        _autodetect_version_targets,
        _describe_version_target,
        _detect_lock_and_files,
        _find_python_version_files,
        _json_string_field_exists,
        _load_raw_config,
        _recommended_lock_settings,
        _render_recommended_rrt_dict,
        _render_recommended_rrt_toml,
        _target_ecosystem,
        _toml_string_field_exists,
        auto_detect_config,
        autodetect_config,
        find_changelog_file,
        find_config_file,
        find_explicit_config_file,
        find_repo_root,
        format_autodetected_config_notice,
        format_missing_tool_rrt_guidance,
        ignore_dir_names,
        is_missing_tool_rrt_error,
        iter_config_files,
        load_config,
        load_config_from_path,
        load_extra_branch_types,
        load_or_autodetect_config,
        load_primary_remote,
        recommend_init_config,
        recommend_init_config_for_go,
        recommend_init_section_for_cargo,
        recommend_init_section_for_node,
        recommend_init_section_for_pyproject,
    )

_core.__path__ = __path__
_core.__package__ = __name__
sys.modules[__name__] = _core
