"""Schema-to-TOML config reference generator for rrt.

Converts the bundled ``[tool.rrt]`` JSON schema into a deterministic,
annotated ``.rrt.toml`` reference text that is both human-readable and
parseable by :mod:`tomllib` without modification.

This module is intentionally pure (no I/O) and has no runtime dependencies
beyond the Python standard library.  It is the single source of truth for
``docs/rrt-config-reference.toml``.

Design notes for ``$ref`` handling
-----------------------------------
The real bundled schema uses ``$ref`` (e.g. ``#/properties/version_targets``)
inside ``version_groups[].version_targets``.  Rather than building a general
JSON-Schema ``$ref`` resolver (which would pull in complexity with no test
coverage benefit), properties that consist *only* of a ``$ref`` key are
**skipped** and a ``# ($ref — see the referenced section for details)``
comment is emitted in their place.  This keeps the generator simple and
robust, and the root-level definitions are still rendered in their own
sections; no information is lost for the end reader.
"""

from __future__ import annotations

import textwrap
from typing import Any

__all__ = ["render_reference_toml"]

_HEADER = "# Generated by 'rrt config reference' — do not edit by hand."
_WRAP_WIDTH = 78  # column limit for description comment wrapping


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_reference_toml(schema: dict[str, Any]) -> str:
    """Return a deterministic annotated TOML string derived from *schema*.

    The returned string is guaranteed to be parseable by :func:`tomllib.loads`
    without error.  Keys are emitted in sorted order for determinism.

    In TOML, once a ``[table]`` or ``[[array-of-tables]]`` header is written,
    all subsequent bare ``key = value`` lines belong to that table.  To avoid
    silent mis-nesting, all scalar / scalar-array properties are emitted
    *before* all table-producing properties at every recursion level
    (two-pass ordering).

    Args:
        schema: A JSON Schema ``object`` whose ``"properties"`` key maps
            property names to their sub-schemas.  Schemas without a
            ``"properties"`` key produce only the header and ``[tool.rrt]``
            table declaration.

    Returns:
        A multi-line TOML string starting with the canonical ``# Generated
        by …`` comment, followed by a blank line and ``[tool.rrt]``, then
        one annotated entry per property.
    """
    lines: list[str] = [_HEADER, "", "[tool.rrt]"]

    props: dict[str, Any] = schema.get("properties", {})
    names = sorted(props)
    ordered = [n for n in names if not _is_table(props[n])] + [
        n for n in names if _is_table(props[n])
    ]
    for name in ordered:
        prop = props[name]
        lines.extend(_render_property(name, prop, parent="tool.rrt"))

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _is_table(prop: dict[str, Any]) -> bool:
    """Return True if *prop* renders as a TOML table or array-of-tables header.

    In TOML, once such a header is written every subsequent bare ``key =
    value`` line belongs to that table.  Knowing which properties are
    "table-producing" lets callers emit all scalars first (two-pass ordering)
    to prevent silent mis-nesting.

    ``$ref``-only properties are treated as non-tables: they emit only a
    comment line (no header, no ``key = value``), so their position in the
    output does not affect nesting.

    Args:
        prop: A JSON Schema sub-schema dict.

    Returns:
        ``True`` for ``type == "object"`` or ``type == "array"`` with
        ``items.type == "object"``; ``False`` for everything else (scalars,
        scalar arrays, ``$ref``-only entries).
    """
    t = prop.get("type")
    if t == "object":
        return True
    if t == "array":
        items = prop.get("items", {})
        return isinstance(items, dict) and items.get("type") == "object"
    return False


def _render_property(
    name: str,
    prop: dict[str, Any],
    parent: str,
) -> list[str]:
    """Render a single property as TOML lines (comment + value/block).

    Args:
        name: The property key name.
        prop: The JSON Schema sub-schema for this property.
        parent: Dotted TOML table path of the containing table
            (e.g. ``"tool.rrt"`` or ``"tool.rrt.eol"``).

    Returns:
        A list of TOML lines (without trailing newline on each) to be joined
        later.  Always starts with a blank separator line.
    """
    # Properties that are *only* a $ref are skipped (see module docstring).
    if set(prop.keys()) <= {"$ref"}:
        return [
            "",
            f"# {name}: ($ref — see the referenced section for details)",
        ]

    lines: list[str] = [""]  # blank separator before each property

    # -- description comment --------------------------------------------------
    description = prop.get("description", "")
    if description:
        lines.extend(_wrap_comment(description))

    # -- enum hint comment ----------------------------------------------------
    enum_vals = prop.get("enum")
    if enum_vals is not None:
        sorted_enums = sorted(str(v) for v in enum_vals)
        lines.append(f"# one of: {', '.join(sorted_enums)}")

    # -- value / sub-block ----------------------------------------------------
    prop_type = prop.get("type")

    if prop_type == "array":
        items = prop.get("items", {})
        if items.get("type") == "object":
            # [[tool.rrt.<name>]] block with one example entry
            qualified = f"{parent}.{name}"
            lines.append(f"[[{qualified}]]")
            sub_props: dict[str, Any] = items.get("properties", {})
            sub_names = sorted(sub_props)
            sub_ordered = [n for n in sub_names if not _is_table(sub_props[n])] + [
                n for n in sub_names if _is_table(sub_props[n])
            ]
            for sub_name in sub_ordered:
                sub_prop = sub_props[sub_name]
                lines.extend(_render_property(sub_name, sub_prop, parent=qualified))
        else:
            # scalar array — emit as empty list
            lines.append(f"{name} = []")

    elif prop_type == "object":
        # [tool.rrt.<name>] sub-table
        qualified = f"{parent}.{name}"
        lines.append(f"[{qualified}]")
        sub_props = prop.get("properties", {})
        sub_names = sorted(sub_props)
        sub_ordered = [n for n in sub_names if not _is_table(sub_props[n])] + [
            n for n in sub_names if _is_table(sub_props[n])
        ]
        for sub_name in sub_ordered:
            sub_prop = sub_props[sub_name]
            lines.extend(_render_property(sub_name, sub_prop, parent=qualified))

    else:
        # Scalar or unrecognised type — emit name = <placeholder>
        lines.append(f"{name} = {_placeholder(prop)}")

    return lines


def _placeholder(prop: dict[str, Any]) -> str:
    """Return a TOML-literal placeholder value for a scalar property.

    Priority order:
    1. If *prop* has ``enum``, use the first sorted enum value
       (quoted if string, bare otherwise).
    2. Dispatch on ``prop["type"]``: ``string`` → ``"..."``,
       ``integer`` / ``number`` → ``0``, ``boolean`` → ``false``.
    3. Fallback for unknown / missing types: ``"..."``.

    Args:
        prop: A JSON Schema sub-schema for a scalar property.

    Returns:
        A TOML-literal string (e.g. ``'"..."'``, ``'0'``, ``'false'``).
    """
    enum_vals = prop.get("enum")
    if enum_vals is not None:
        first = sorted(str(v) for v in enum_vals)[0]
        # In the real schema all enum values are strings; quote them.
        return f'"{first}"'

    prop_type = prop.get("type", "string")
    if prop_type == "string":
        return '"..."'
    if prop_type in ("integer", "number"):
        return "0"
    if prop_type == "boolean":
        return "false"
    # Fallback: treat as string
    return '"..."'


def _wrap_comment(text: str) -> list[str]:
    """Wrap *text* into ``# …`` comment lines at :data:`_WRAP_WIDTH` columns.

    Args:
        text: The raw description string to wrap.

    Returns:
        A list of comment lines, each prefixed with ``"# "``.
    """
    # textwrap.wrap respects word boundaries and the "# " prefix (2 chars)
    # within the total column budget.
    wrapped = textwrap.wrap(text, width=_WRAP_WIDTH - 2)  # account for "# "
    return [f"# {line}" for line in wrapped] if wrapped else [f"# {text}"]
